### ISSUE TITLE
Get chat messages JSON

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#12]
Pokud odešlu nějakou chat zpávu na server, a pak se snažím ji příjmout, dostavám tuto chybovou hlášku
11-20 16:47:10.931: E/MessageQueue(3257): org.json.JSONException: Value [{"id":"38","type":"chat","data":"kjkj"},{"id":"39","type":"chat","data":"kjkj"},{"id":"40","type":"chat","data":"kjkj"},{"id":"41","type":"chat","data":"kjkj"},{"id":"42","type":"chat","data":"kjkj"}] of type org.json.JSONArray cannot be converted to JSONObject

Nevím jestli musí se něco upravit na serveru nebo v Javě. 
pushnul jsem kód pomocí kterého přídavám message, čtu message

**Comment by NoxArt** [comment]
Spí¹ v Jave, zítra opravim
Dne 21.11.2013 1:33 "IevgenRagulin" notifications@github.com napsal(a):

**Comment by IevgenRagulin** [comment]
už jsem právě šel spat :D

**Comment by NoxArt** [comment]
mělo být spíš ;)

udělal jsem řadu oprav, tak teď už to tahá zprávy, jak chat, tak ostatní

do logu už se taky zapisují odesílané požadavky na server

**Comment by IevgenRagulin** [comment]
ted' jsem si všíml, že zapoměl jsem včera pushnut.. ted trochu máme konflikty, ale asi to bude v pořádku

**Comment by NoxArt** [comment]
Okey, tak to prosím před commitem zkontroluj
