### ISSUE TITLE
Words DB

### ISSUE THREAD

**Issue by tomasdavidorg** [NoxArt/CityNameAnimal#13]
Podařilo se mi sehnat a upravit seznam českých jmen, rostlin, živočichů a měst, ale sehnat seznam věcí je nereálné. 
Stejně tak anglická db měst, rostlin, věcí (jména rostliny živočichové by možná šly).
Ale viděl bych to spíš tak že by jsme měli jen českou databázi s tím že databáze věcí vymyslím (třeba 10 věcí co mě první napadne k písmenu).
Může to tak být? Nebo máte jiný nápad?

**Comment by tomasdavidorg** [comment]
Tak už mám i věci.
Vzal jsem český slovník a pomocí SEDu jsme postupně odstraňoval slova končící na ový, natý, vý, ... atd.
Prostě jsme to zúžil z nějakých 1660000 slov na nějakých 50000. Asi to nejsou všechno věci, ale většina snad je :-D.
Otázka na anglický slovník stále platí. Ale doufám že ho nebudeme chtít :-D.

**Comment by IevgenRagulin** [comment]
Žádný anglický slovník nechci :) český stačí

**Comment by NoxArt** [comment]
Tak ten atribut jazyka nás nezabije, on tam relativně je

Mluvili jsme o tom, že by db teda byla online? Přístup k DB bys měl mít, tak to tam můžeš hodit

**Comment by tomasdavidorg** [comment]
asi jo dal bych to online... ten pristup nemam, nebo jsi mi ho uz posilal, posli mi jej radeji znovu :-) diky

**Comment by tomasdavidorg** [comment]
na mail jsem ti poslal ty skripty na vytvoreni db a jeji naplneni... pokud by jsi to nejak chtel upravit tak mi rekni

**Comment by NoxArt** [comment]
Díky. Oproti definici ve words tabulce tam chybí v definicích sloupec category, šlo by to doplnit?

**Comment by tomasdavidorg** [comment]
Asi nevim co myslis ... kategorie je definovana i vkladana

**Comment by tomasdavidorg** [comment]
asi jsem ti poslal blby skript na tabulu:

CREATE TABLE IF NOT EXISTS `words` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `word` varchar(50) COLLATE latin2_czech_cs NOT NULL,
  `category` enum('jmeno','mesto','zvire','vec','rostlina') COLLATE latin2_czech_cs NOT NULL,
  `language` enum('cz','en') COLLATE latin2_czech_cs NOT NULL,
  `firstletter` varchar(1) COLLATE latin2_czech_cs NOT NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

Tohle jsi myslel?

**Comment by NoxArt** [comment]
Zkusím

**Comment by NoxArt** [comment]
Jo, už ok. První písmena jsou s diakritikou, ale pokud je toto správně http://stackoverflow.com/a/4813651 tak by to neměl být problém
