### ISSUE TITLE
Game fails when no internet connection is active.

### ISSUE THREAD

**Issue by tomasdavidorg** [NoxArt/CityNameAnimal#14]
Vyvola se vyjimka java.net.UnknownHostException. Asi to tam jeste neosetrujete, ze? Pridavam to sem jen aby se na to nezapomnelo. :-)

**Comment by IevgenRagulin** [comment]
Jojo, zatím to neošetřujeme... Takových bagů ted' je asi milion)

**Comment by NoxArt** [comment]
Nevím jestli řešit ztrátu a obnovení připojení uprostřed ... jestli se to bude předvádět v té hloupé G202, tak to možná bude potřeba. Zatím nevim, jak to elegantně řešit (hlavně tím, že to běží asynchronně)

**Comment by IevgenRagulin** [comment]
Zkusil jsem opravit tu chybu. Ale to testovani na emulatoru trva 10krat víc než odstranění té chyby, a už nemám na ten emulator nervy :)
