### ISSUE TITLE
Přihlášení předvedení projektu ve WISu

### ISSUE THREAD

**Issue by tomasdavidorg** [NoxArt/CityNameAnimal#17]
Přihlásíme se až na termín za dva týdny (10. 12.), ne?
Popř. mohl by to někdo přihlásit, v tu dobu nebudu mít po ruce internet.

**Comment by IevgenRagulin** [comment]
taky asi nebudu mít internet v 20.00

**Comment by NoxArt** [comment]
Já budu skoro určitě, takže ... se pak ještě domluvíme na Skype, pokud nebudeš na Skype, tak regnu (snad půjdou vidět ostatní registrace)

Klidně mi to ještě předtím připomeňte

Určitě druhý termín, kdyby šel dát leden, tak dám leden :)
