### ISSUE TITLE
Prezentace

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#18]
Katka nabidla udělat pro prezentace video. Máme napad že bychom mohli zaznamenat jak hráme tuto hru, mezi tím vložit kratká videa s tím jak nastavujeme jednotlíve parametry hry, vyplnujeme.

Co si myslíte?

Tady napíšeme kratký scenář toho co bychom chtěli udělat. https://docs.google.com/document/d/1BODr18ZeIDaVB3UF3nCTqETyZxqSobj3RjFrrmOT53A/edit

Za hodinku bych jel do Katky abychom udělali video. Možna někdo by se také chtěl zůčastnit?

**Comment by NoxArt** [comment]
*ke Katce

No ale když to ještě nemáme?

**Comment by IevgenRagulin** [comment]
Uděláme zatím záznam jen toho co máme.. Pak to asi nebude problém vložit..

**Comment by NoxArt** [comment]
Ok, dobře. Část hodnocení už mám, zatím neotestováno

**Comment by NoxArt** [comment]
Spíš nevim, co napsat do těch rad a toho "co se nám osvědčilo"...

**Comment by IevgenRagulin** [comment]
Také nevím. Ani nevím co znamená "co se nám osvědčilo")) jen mi napada to, že příště bych před začatkém praci nad android aplikace přečetl nějaké best practices pro organizace kódu v androidu. Třeba nějaký MVC. Protože ted' to je ok, ale kdyby projekt byl trochu větší, tak ja bych se asi ztratil v tom kódu Activity. Musel by ještě asi byt nějaký kontroller..

**Comment by NoxArt** [comment]
Jo ... ty Activity v Androidu jsou moc blízko View, no... osobně bych Activity nechal jako Controller a tu práci s View přesunul ještě někam.

"Co se nám osvědčilo" = "které postupy/techniky(případně /programy atd.) se v průběhu tvorby ukázaly jako výhodné" (případně doplnit které ne).

**Comment by IevgenRagulin** [comment]
Jen ted' jsem uviděl žes mi opravil)) Díky. Dá se také říct za Katkou?

**Comment by NoxArt** [comment]
V pohodě. Ano, to taky

**Comment by tomasdavidorg** [comment]
ahoj omlouvám se ale az ted jsem se vratil z budoshow... je neco jak bych mohl prispet? ... + pocitam s tim ze v utery klidne muzu zase vest tu prezentaci

**Comment by xrofma00** [comment]
Ahoj, Tome, mohla bych s tebou taky prezentovat! ))

**Comment by NoxArt** [comment]
Ahoj, tak tím spíš jestli bys teda napsal i slidy, ať je budeš znát. Hlavně teda vymyslet, co jsme se na tom naučili ;)

**Comment by xrofma00** [comment]
Teď s Jevgenem natačíme video prezenteci hry, tak to bude sranda, doufam že se vám bude libit.

**Comment by tomasdavidorg** [comment]
:-)

**Comment by tomasdavidorg** [comment]
https://docs.google.com/presentation/d/1XAuOpjtdv5jaIv5HhjjlHfL0-5yhR32nj_lOWY5OBgE/edit?usp=sharing
