### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#19]
Zkusil jsem ted' jestli funguje chat. 

Tady je post
12-01 09:57:05.133: W/post_message(1401): data=User%3A+hi+guyes&command=post_message&type=chat&token=mde0p3kgir4oaapns6mcmnswegsnwm&game_id=206

Tady je nasledně get
12-01 09:57:05.703: W/get_messages(1401): {"result":[{"id":"967","type":"chat","data":null}]}

V databaze zpráva je, ale ve sloupci data je null

**Comment by NoxArt** [comment]
Díky, mrknu na to

**Comment by NoxArt** [comment]
Opravil jsem, zkus prosím

**Comment by IevgenRagulin** [comment]
Díky, funguje
