### ISSUE TITLE
Databaze slov

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#20]
Není to chyba? Jsou to věcí?
19085   Ivonka  vec cz  I
19086   Ivo vec cz  I
19087   IX  vec cz  I
19088   Izabela vec cz  I
19089   Izabelin    vec cz  I
19090   Izaiáš    vec cz  I
19091   Izák   vec cz  I
19092   Izmir   vec cz  I
19106   Izolda  vec cz  I
19116   Izraelka    vec cz  I
19117   Izrael

**Comment by tomasdavidorg** [comment]
no ty veci nejsou uplne perfektni sehnat databazi veci je problem... je mozne ze tam jsou blbosti

**Comment by NoxArt** [comment]
Asi, ale nikdo to zkoumat nebude
