### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#22]
Založil jsem tady dokument pro vytvoření dokumentace. Na strankach předmětu je šablona, což nám zjednodušuje práce.
https://docs.google.com/document/d/1rhFHv-ZOG808_MwmqwgAztcI3kfCl2etQdyzmp8ynrw/edit

Napište tady prosím vaše emaily nebo kliknete na ten link a zmáčknete tam request access

**Comment by IevgenRagulin** [comment]
Začal jsem pracovat na dokumentaci. Omlouvám se za své chyby v češtině. Mažte, doplňujte.

**Comment by tomasdavidorg** [comment]
Něco jsem tam upravil ale dnes už musím jít ... zítra odpoledne to doplním a upravím.

**Comment by tomasdavidorg** [comment]
Mrknete prosim jeste na tu sekci "Pět základních otázek TAMu" a neco tam doplnit zkusim jeste neco vymyslet ale nevim kolik me toho napadne. Diky.

**Comment by IevgenRagulin** [comment]
Jak rozumíte otáze "Čím žije tento sektor IT?" Znamená to jake jsou trendy ted'? Nebo jak vydělavaji trůrci aplikací?

**Comment by NoxArt** [comment]
Spíš to jaké jsou trendy
