### ISSUE TITLE
Odevzdání

### ISSUE THREAD

**Issue by tomasdavidorg** [NoxArt/CityNameAnimal#23]
Ahoj,
dneska musíme odevzdat projekt.Nevím jestli se to má odevzdávat do wisu nebo posílat mu na mail, každopádně je potřeba to zkompletovat. Hned jak se vrátím z práce (cca v 17h) tak zkontroluju dokumentaci na pravopisné chyby a pokusím se to dát dohromady.

**Comment by IevgenRagulin** [comment]
Myslel jsem si že musíme odevzdat projekt až v neděli. Ale budu rád když odevzdáme ho dnes

**Comment by tomasdavidorg** [comment]
Ve wisu je 15.12 ale na private stránkách je "Projekty odevzdávejte do 13.12.2012!!". Takže raději odevzdejme dnes.
