### ISSUE TITLE
Ten server, který jsi dělal, běží na tvém počítači lokálně nebo máš ho někde na webu?

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#4]
Pokud je na webu, prosím o odkazu :)

**Comment by NoxArt** [comment]
Aha, myslel jsem, že tam někde je uvedený.

Běží online na: http://fit.noxart.cz/tam/

Dále je zprovozněný přístup k DB: http://adminer.noxart.cz
Údaje jsou v config.php

Seznam příkazů zde: https://github.com/NoxArt/CityNameAnimal/wiki/Commands

Počítá s metodou POST

Teoreticky je už přes model možno zasílat cokoli, ale interface a obalující metody jsou zatím pro get_games, teoreticky pak create_game, get_messages, send_message.

**Comment by IevgenRagulin** [comment]
Super, díky! Mohl bys prosím ještě napsat kde najdu config.php?

**Comment by NoxArt** [comment]
Poslal jsem ti na FIT mail, přístupy bych nerad dával veřejně sem
