### ISSUE TITLE
GameProperties konstruktor

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#5]
V konstruktoru GameProperties, kromě toho, co je popsaný tady https://docs.google.com/document/d/1GWJUMFdQv5MD9Fx2uk6CCzxESYtJEPXJi_UK6oGHiW8/edit

také jsou timeLimit, roundLimit, playerLimit, language. Kdo nastavuje toto? Uživatel který vytváří hru?

**Comment by IevgenRagulin** [comment]
V jakých časových jednotkách musí byt timeLimit, roundLimit? milliseconds? seconds?

**Comment by NoxArt** [comment]
Ano, to jsou hodnoty, co se zadávají ve tvé obrazovce nová hra (asi kromě language, ten bude nejspíš globální, i když by bylo asi lepší mít ho tam). Může to být přitom, anebo při getGames, tam se vytvoří řada instancí GameProperties s těmito hodnotami na základě údajů z databáze serveru

Zapomněl jsem okomentovat :/

TimeLimit v seconds, roundLimit bez jednotky, tzn. počet kol
