### ISSUE TITLE
Dá se nějak podívat na log serveru, databáze?

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#7]
Nedaří se mi vytvořit hru. Na řádku 66, v GameClient.createGame()

JSONObject identifiers = messaging.sendMessage(arguments);
Log.info(identifiers);

V logu vypisuje:
JSON RESPONSE(2960): {"error":"Game with provided ID not found"}

Kvůli tomu si myslím, že vytvořeni hry se nezdařilo, a pak nemůže se na tu hru přihlásit, protože hra neexistuje.

Proto se ptám jestli dá se nějak podívat na log serveru abych zjistil, co dělám špatně.

**Comment by IevgenRagulin** [comment]
Tady jsou parametry které se odesílají na server v HttpConnect.post
11-16 10:14:08.822: V/JSON REQUEST(3132): round_limit=1&time_limit=90&name=a&command=create_game&categories=Mesto&language=cz&player_limit=5&evaluation=auto

**Comment by NoxArt** [comment]
Mělo by to být opravené, ale nejde mi to na tomto PC testovat, tak to zkus prosím u sebe (pushnul jsem, tak updatni). Na serveru zkusím zlepšit info

**Comment by IevgenRagulin** [comment]
Díky. Pomohlo to. Udělal jsem ještě malou úpravu v GameClient a asi se hra už vytváří (v databaze je), a server vrací odpověd' {"player_token":"cl1rlt5mna12t9xv7ie5y8hgz2qhiz","id":"8","player_id":1,"admin_token":"c178icqdi3ykfkh139tljr2yijrpvf"}
